from sage.all import *
from itertools import combinations

# ============================================================================
# EVOLVING SPECTRAL-CONNECTION TEST
# ============================================================================
#
# Run in the SAME SageMath session after successful cells 13--21.
#
# PURPOSE
# -------
# Every degree-two potential, contact, block-log, Kähler-square, and symmetric
# second-order HSS-operator deformation tested so far leaves one response
# direction unexplained.  All previous closure tests nevertheless assumed that
# the order-p^2 shifts of the two leading spectral channels were CONSTANT:
#
#     alpha_1, beta_1 in RR.
#
# This cell tests the more geometric possibility that they are connection
# coefficients varying along the radial modulus X:
#
#     alpha_1 = alpha_1(X),    beta_1 = beta_1(X).
#
# The natural affine factors already present in the geometry are
#
#     U = 3 X + 1       (because V(X,1,1)=3U),
#     W = 2 X + 1       (because the even vector is (-(2X+1),1,1)).
#
# We test Laurent-polynomial coefficient modules generated by U^k and W^k,
# k = +/-1,+/-2,+/-3.  Constants k=0 are already the old alpha_1,beta_1
# columns.  The combined U/W family has only 24 new columns; with the five old
# columns this remains below the 33 independent radial equations used here, so
# any closure is non-row-saturated.
#
# ROBUSTNESS
# ----------
# * Reuses the 21 points from cell 21.
# * Adds 12 new held-out rational X-values.
# * Reports training and combined ranks separately.
# * A formula is printed only if it closes all 33 equations.
# ============================================================================

print("="*78, flush=True)
print("EVOLVING DEGREE-TWO SPECTRAL-CONNECTION TEST", flush=True)
print("Allowing alpha_1(X) and beta_1(X) to vary over natural radial factors", flush=True)
print("="*78, flush=True)
print(flush=True)

required_names = [
    "RF", "alpha0", "beta0", "component_data_at_X",
    "ALL_POINTS", "KNOWN_ROWS", "KNOWN_RHS",
    "numerical_rref", "equilibrate_system",
]
missing = [name for name in required_names if name not in globals()]
if missing:
    raise RuntimeError(
        "Run cells 13 through 21 first in the same Sage session. Missing: {}"
        .format(missing)
    )

RANK_TOL_EXPONENT = 70
RANK_TOL = RF(10)**(-RANK_TOL_EXPONENT)
LAURENT_DEGREE = 3
LAURENT_EXPONENTS = [
    exponent
    for exponent in range(-LAURENT_DEGREE, LAURENT_DEGREE+1)
    if exponent != 0
]

# New points are deliberately disjoint from cells 13 and 21.
CONNECTION_VALIDATION_X = [
    QQ(1)/2,
    QQ(3)/5,
    QQ(5)/6,
    QQ(7)/6,
    QQ(7)/5,
    QQ(5)/3,
    QQ(11)/5,
    QQ(8)/3,
    QQ(10)/3,
    QQ(9)/2,
    QQ(7),
    QQ(8),
]

TRAIN_POINTS = list(ALL_POINTS)
ALL_CONNECTION_POINTS = list(TRAIN_POINTS)
for value in CONNECTION_VALIDATION_X:
    if value not in ALL_CONNECTION_POINTS:
        ALL_CONNECTION_POINTS.append(value)

TRAIN_COUNT = len(TRAIN_POINTS)
TOTAL_COUNT = len(ALL_CONNECTION_POINTS)
VALIDATION_COUNT = TOTAL_COUNT - TRAIN_COUNT

print("Working real precision: {} bits".format(RF.precision()), flush=True)
print("Existing training equations: {}".format(TRAIN_COUNT), flush=True)
print("New validation equations: {}".format(VALIDATION_COUNT), flush=True)
print("Total radial equations: {}".format(TOTAL_COUNT), flush=True)
print("Laurent powers: {}".format(LAURENT_EXPONENTS), flush=True)
print(flush=True)


def max_abs_22(values):
    values = list(values)
    if not values:
        return RF(0)
    return max(abs(RF(value)) for value in values)


def rank_pair_22(A_rows, rhs_values, tolerance=RANK_TOL):
    A_eq, b_eq, _ = equilibrate_system(A_rows, rhs_values)
    augmented = [row + [rhs] for row, rhs in zip(A_eq, b_eq)]
    return (
        len(numerical_rref(A_eq, tolerance)[1]),
        len(numerical_rref(augmented, tolerance)[1]),
    )


def compact_rank_profile_22(A_rows, rhs_values):
    decimal_digits = max(20, int(RF.precision()*0.3010299956639812))
    exponents = [30, 70, 120, 192, min(345, decimal_digits-10)]
    exponents = sorted(set(e for e in exponents if 10 <= e <= decimal_digits-10))
    return [
        (exponent,) + rank_pair_22(A_rows, rhs_values, RF(10)**(-exponent))
        for exponent in exponents
    ]


def canonical_full_solution_22(A_rows, rhs_values, tolerance=RANK_TOL):
    """Canonical solution: set every free equilibrated variable to zero."""
    A_eq, b_eq, column_scales = equilibrate_system(A_rows, rhs_values)
    augmented = [row + [rhs] for row, rhs in zip(A_eq, b_eq)]
    R_A, pivots_A = numerical_rref(A_eq, tolerance)
    R_aug, pivots_aug = numerical_rref(augmented, tolerance)

    if len(pivots_A) != len(pivots_aug):
        return None

    n_columns = len(A_rows[0])
    z = [RF(0)]*n_columns
    for row_index, pivot in enumerate(pivots_A):
        z[pivot] = R_aug[row_index][-1]

    return [z[index]/column_scales[index] for index in range(n_columns)]


def residuals_22(A_rows, rhs_values, solution):
    return [
        sum(RF(a)*RF(x) for a, x in zip(row, solution)) - RF(rhs)
        for row, rhs in zip(A_rows, rhs_values)
    ]


# ----------------------------------------------------------------------------
# Extend the old five-column response system to the 12 new validation points.
# Column convention:
#   [rA, rB, rC, -sigma_1, -D_1],  rhs=-Rquad.
# ----------------------------------------------------------------------------

BASE_ROWS = [list(row) for row in KNOWN_ROWS]
BASE_RHS = [RF(value) for value in KNOWN_RHS]

print("Building the old response system at new validation points...", flush=True)
for index, X_value in enumerate(CONNECTION_VALIDATION_X, start=1):
    base = component_data_at_X(X_value, None)
    colA = component_data_at_X(X_value, "A")
    colB = component_data_at_X(X_value, "B")
    colC = component_data_at_X(X_value, "C")

    def corrected(total):
        return RF(
            total["Scurv2"] - base["Scurv2"]
            - alpha0*total["sigma2"] - beta0*total["D2"]
        )

    BASE_ROWS.append([
        corrected(colA),
        corrected(colB),
        corrected(colC),
        RF(-base["sigma1"]),
        RF(-base["D1"]),
    ])
    BASE_RHS.append(RF(-base["Scurv2"]))
    print("  completed {}/{} at X={}".format(
        index, len(CONNECTION_VALIDATION_X), X_value
    ), flush=True)

if len(BASE_ROWS) != TOTAL_COUNT:
    raise ArithmeticError("Expanded base-row count is inconsistent.")

base_train_rank = rank_pair_22(BASE_ROWS[:TRAIN_COUNT], BASE_RHS[:TRAIN_COUNT])
base_all_rank = rank_pair_22(BASE_ROWS, BASE_RHS)

print(flush=True)
print("Baseline checks:", flush=True)
print("  training: rank(A)={} rank([A|b])={}".format(*base_train_rank), flush=True)
print("  all 33:  rank(A)={} rank([A|b])={}".format(*base_all_rank), flush=True)
print(flush=True)

if base_train_rank != (4, 5) or base_all_rank != (4, 5):
    raise ArithmeticError("The old response system did not retain rank 4/5.")


# ----------------------------------------------------------------------------
# Candidate evolving connection columns.
# ----------------------------------------------------------------------------

CANDIDATE_COLUMNS = {}
CANDIDATE_META = {}

for factor_name in ["U", "W"]:
    for exponent in LAURENT_EXPONENTS:
        sigma_name = "alpha_{}_{}".format(factor_name, exponent)
        beta_name = "beta_{}_{}".format(factor_name, exponent)

        sigma_column = []
        beta_column = []

        for X_value, base_row in zip(ALL_CONNECTION_POINTS, BASE_ROWS):
            Xv = RF(X_value)
            factor = RF(3)*Xv + RF(1) if factor_name == "U" else RF(2)*Xv + RF(1)
            multiplier = factor**exponent

            # base_row[-2] = -sigma_1; base_row[-1] = -D_1.
            sigma_column.append(multiplier*RF(base_row[-2]))
            beta_column.append(multiplier*RF(base_row[-1]))

        CANDIDATE_COLUMNS[sigma_name] = sigma_column
        CANDIDATE_COLUMNS[beta_name] = beta_column
        CANDIDATE_META[sigma_name] = ("alpha", factor_name, exponent)
        CANDIDATE_META[beta_name] = ("beta", factor_name, exponent)


U_NAMES = [
    name for name, meta in CANDIDATE_META.items()
    if meta[1] == "U"
]
W_NAMES = [
    name for name, meta in CANDIDATE_META.items()
    if meta[1] == "W"
]
ALL_NAMES = U_NAMES + W_NAMES


def assemble_connection_system_22(names, row_count=TOTAL_COUNT):
    return [
        list(BASE_ROWS[row]) + [CANDIDATE_COLUMNS[name][row] for name in names]
        for row in range(row_count)
    ]


def test_connection_family_22(label, names, verbose=True):
    A_train = assemble_connection_system_22(names, TRAIN_COUNT)
    A_all = assemble_connection_system_22(names, TOTAL_COUNT)

    train_pair = rank_pair_22(A_train, BASE_RHS[:TRAIN_COUNT])
    all_pair = rank_pair_22(A_all, BASE_RHS)
    closes = bool(all_pair[0] == all_pair[1])
    saturated = bool(all_pair[0] == TOTAL_COUNT)
    structural = bool(closes and not saturated)

    if verbose:
        print("-"*78, flush=True)
        print(label, flush=True)
        print("  new connection columns: {}".format(len(names)), flush=True)
        print("  training rank(A)={} rank([A|b])={}".format(*train_pair), flush=True)
        print("  all-point rank(A)={} rank([A|b])={}".format(*all_pair), flush=True)
        print("  connection quotient rank: {}".format(all_pair[0]-4), flush=True)
        print("  closes all 33 equations? {}".format(closes), flush=True)
        print("  row-saturated interpolation? {}".format(saturated), flush=True)
        print("  non-saturated structural closure? {}".format(structural), flush=True)
        print("  stable all-point rank profile:", flush=True)
        for exponent, rA, rAug in compact_rank_profile_22(A_all, BASE_RHS):
            print("    1e-{:<4d}: rank(A)={} rank([A|b])={}".format(
                exponent, rA, rAug
            ), flush=True)

    return {
        "label": label,
        "names": list(names),
        "A_train": A_train,
        "A_all": A_all,
        "train_pair": train_pair,
        "all_pair": all_pair,
        "closes": closes,
        "saturated": saturated,
        "structural": structural,
    }


print("Evolving-connection reachability ladder:", flush=True)

FAMILY_RESULTS = {}
FAMILY_RESULTS["U"] = test_connection_family_22(
    "U=3X+1 LAURENT CONNECTION MODULE", U_NAMES
)
FAMILY_RESULTS["W"] = test_connection_family_22(
    "W=2X+1 LAURENT CONNECTION MODULE", W_NAMES
)
FAMILY_RESULTS["UW"] = test_connection_family_22(
    "COMBINED U/W LAURENT CONNECTION MODULE", ALL_NAMES
)

# Fixed leading combination gamma(X)*(alpha0*sigma_1+beta0*D_1).
COMMON_NAMES = []
COMMON_COLUMNS = {}
for factor_name in ["U", "W"]:
    for exponent in LAURENT_EXPONENTS:
        name = "gamma_{}_{}".format(factor_name, exponent)
        alpha_name = "alpha_{}_{}".format(factor_name, exponent)
        beta_name = "beta_{}_{}".format(factor_name, exponent)
        COMMON_NAMES.append(name)
        COMMON_COLUMNS[name] = [
            alpha0*CANDIDATE_COLUMNS[alpha_name][row]
            + beta0*CANDIDATE_COLUMNS[beta_name][row]
            for row in range(TOTAL_COUNT)
        ]


def assemble_common_system_22(names, row_count=TOTAL_COUNT):
    return [
        list(BASE_ROWS[row]) + [COMMON_COLUMNS[name][row] for name in names]
        for row in range(row_count)
    ]


A_common_train = assemble_common_system_22(COMMON_NAMES, TRAIN_COUNT)
A_common_all = assemble_common_system_22(COMMON_NAMES, TOTAL_COUNT)
common_train_pair = rank_pair_22(A_common_train, BASE_RHS[:TRAIN_COUNT])
common_all_pair = rank_pair_22(A_common_all, BASE_RHS)
common_closes = bool(common_all_pair[0] == common_all_pair[1])

print("-"*78, flush=True)
print("FIXED LEADING-COMBINATION CONNECTION MODULE", flush=True)
print("  channel: gamma(X)*(alpha0*sigma_1+beta0*D_1)", flush=True)
print("  new connection columns: {}".format(len(COMMON_NAMES)), flush=True)
print("  training rank(A)={} rank([A|b])={}".format(*common_train_pair), flush=True)
print("  all-point rank(A)={} rank([A|b])={}".format(*common_all_pair), flush=True)
print("  closes all 33 equations? {}".format(common_closes), flush=True)
print("  non-saturated structural closure? {}".format(
    common_closes and common_all_pair[0] < TOTAL_COUNT
), flush=True)


# ----------------------------------------------------------------------------
# If the full independent module closes, isolate a canonical formula and then
# reduce to quotient-pivot connection columns before searching for a minimal
# subset.  No subset can close when the full module is inconsistent.
# ----------------------------------------------------------------------------

full_result = FAMILY_RESULTS["UW"]
minimal_closers = []

if full_result["closes"]:
    full_solution = canonical_full_solution_22(full_result["A_all"], BASE_RHS)
    if full_solution is None:
        raise ArithmeticError("Consistent full connection system had no solution.")

    full_residual = max_abs_22(residuals_22(
        full_result["A_all"], BASE_RHS, full_solution
    ))

    print(flush=True)
    print("Canonical full-module solution:", flush=True)
    print("  max all-point residual = {}".format(full_residual), flush=True)
    print("  factorized coefficients (a,b,c) = {}".format(
        tuple(full_solution[:3])
    ), flush=True)
    print("  constant alpha_1 = {}".format(full_solution[3]), flush=True)
    print("  constant beta_1  = {}".format(full_solution[4]), flush=True)

    alpha_terms = []
    beta_terms = []
    for offset, name in enumerate(ALL_NAMES):
        coefficient = full_solution[5+offset]
        if abs(coefficient) <= RF(10)**(-60):
            continue
        channel, factor_name, exponent = CANDIDATE_META[name]
        term = (factor_name, exponent, coefficient)
        if channel == "alpha":
            alpha_terms.append(term)
        else:
            beta_terms.append(term)

    print("  nonzero evolving alpha terms:", flush=True)
    for factor_name, exponent, coefficient in alpha_terms:
        print("    {} * {}^{}".format(coefficient, factor_name, exponent), flush=True)
    print("  nonzero evolving beta terms:", flush=True)
    for factor_name, exponent, coefficient in beta_terms:
        print("    {} * {}^{}".format(coefficient, factor_name, exponent), flush=True)

    # Joint RREF determines which candidate columns are genuinely independent
    # modulo the old rank-four response span.
    A_eq, b_eq, _ = equilibrate_system(full_result["A_all"], BASE_RHS)
    _, pivots = numerical_rref(A_eq, RANK_TOL)
    quotient_candidate_indices = [
        pivot-5 for pivot in pivots if pivot >= 5
    ]
    quotient_names = [ALL_NAMES[index] for index in quotient_candidate_indices]

    print("  quotient-pivot connection columns: {}".format(quotient_names), flush=True)

    # Search only within a basis of the full candidate span.  This is enough:
    # every other candidate column is a linear combination modulo the old span.
    for subset_size in range(1, len(quotient_names)+1):
        closers_here = []
        for subset in combinations(quotient_names, subset_size):
            A_subset = assemble_connection_system_22(subset, TOTAL_COUNT)
            pair = rank_pair_22(A_subset, BASE_RHS)
            if pair[0] == pair[1] and pair[0] < TOTAL_COUNT:
                closers_here.append((subset, pair))
        if closers_here:
            minimal_closers = closers_here
            break

    print(flush=True)
    print("Minimal structural connection subsets:", flush=True)
    for subset, pair in minimal_closers:
        print("  {} -> rank(A)={} rank([A|b])={}".format(
            subset, pair[0], pair[1]
        ), flush=True)
else:
    print(flush=True)
    print("The complete independent U/W Laurent connection module is inconsistent.", flush=True)
    print("Therefore no subset of these evolving spectral coefficients can close.", flush=True)


# ----------------------------------------------------------------------------
# Compact summary.
# ----------------------------------------------------------------------------

print(flush=True)
print("="*78, flush=True)
print("EVOLVING SPECTRAL-CONNECTION SUMMARY", flush=True)
print("  family                                  rank(A)  rank([A|b])  structural", flush=True)

for key, label in [
    ("U", "U=3X+1 Laurent module"),
    ("W", "W=2X+1 Laurent module"),
    ("UW", "combined U/W Laurent module"),
]:
    result = FAMILY_RESULTS[key]
    print("  {:<39s} {:>3d}         {:>3d}       {}".format(
        label,
        result["all_pair"][0],
        result["all_pair"][1],
        result["structural"],
    ), flush=True)

print("  {:<39s} {:>3d}         {:>3d}       {}".format(
    "fixed leading-combination module",
    common_all_pair[0],
    common_all_pair[1],
    common_closes and common_all_pair[0] < TOTAL_COUNT,
), flush=True)

print(flush=True)
print("Interpretive diagnostics:", flush=True)
print("  U-Laurent connection closes? {}".format(FAMILY_RESULTS["U"]["closes"]), flush=True)
print("  W-Laurent connection closes? {}".format(FAMILY_RESULTS["W"]["closes"]), flush=True)
print("  combined U/W connection closes? {}".format(full_result["closes"]), flush=True)
print("  fixed leading-combination connection closes? {}".format(common_closes), flush=True)
print("  minimal structural closers: {}".format(
    [subset for subset, _ in minimal_closers]
), flush=True)

print(flush=True)
print("="*78, flush=True)
print("SUCCESS", flush=True)
print("The first radial connection-valued extension of alpha_1 and beta_1", flush=True)
print("was tested on 21 existing and 12 new validation points.", flush=True)
print("Copy the summary and any canonical evolving-coefficient solution back.", flush=True)
print("="*78, flush=True)
